language: node_js
node_js:
- "node"
script:
- npm run build
- npm run test

jobs:
  include:
  - stage: deploy
    script:
    - npm run build
    deploy:
    - provider: pages
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      local-dir: dist/angular-test
      target-branch: gh-pages
      on:
        branch: master
